---
title: "README"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{README}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(classwiseAcor)

data = internal$sampledata[,c("date", "id4")]

# Calculate via "r" method
r_acor = classwiseAcor::acor(
  data = data, 
  method = "r",
  dt = 30, 
  stop = 0.5
)

# Calculate via "c++" method
cpp_acor = classwiseAcor::acor(
  data = data, 
  method = "cpp",
  dt = 30, 
  stop = 0.5
)
```

```{r}
# Plot definition
plot_acor = function(r_acor, cpp_acor) {
  plot(x = 1:nrow(r_acor), y = r_acor$Autocorrelation)
  points(x = 1:nrow(cpp_acor), y = cpp_acor$Autocorrelation, pch = 2)
}

# Make a plot
plot_acor(r_acor, cpp_acor)
```

```{r}
set.seed(100)
zahlen = sin(seq(0, 4*pi, length.out = 60))
# zahlen[sample(1:30, 4)] = NA
zahlen

classwiseAcor::acor(
  data = data.frame(ts = 1:60, data = zahlen), 
  method = "r",
  dt = 6, 
  stop = 0.5
)

classwiseAcor::acor(
  data = data.frame(ts = 1:60, data = zahlen), 
  method = "cpp",
  dt = 6, 
  stop = 0.5
)

```

