# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_classwiseAcor_rcpp_hello_world`)
}

acor_pairs <- function(data, FromTo) {
    .Call(`_classwiseAcor_acor_pairs`, data, FromTo)
}

