# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates pairs of data
#' 
#' @name acor_pairs
#'
#' @param data A data.frame. First column: date, second column: values.
#' @param FromTo Limits for pairing
#'
#' @return Two column matrix of paired data
NULL

acor_pairs <- function(data, FromTo) {
    .Call(`_classwiseAcor_acor_pairs`, data, FromTo)
}

